### ISSUE TITLE
Unable to deploy the Selenosis app.

### ISSUE THREAD

**Issue by ShwethaParthasarathy** [alcounit/selenosis-deploy#9]
Hi,

I am unable to access the hub. When i try to access the url : http://LoadBalancer IP:4444/wd/hub i get 404 page not found. I can see that the end points are correctly listed in service and pods are up and running. I am able to access selenoid-ui  only the hub is the issue. I am using minkube to test the deployment

**Comment by alcounit** [comment]
Hi @ShwethaParthasarathy, that's fine because selenosis doesn't handle /wd/hub endpoint
https://github.com/alcounit/selenosis/blob/afe761964ec20b9bc9a9661bf36b8da9cd870ce3/cmd/selenosis/main.go#L93-L103

If you want session info you can call /wd/hub/status

**Comment by ShwethaParthasarathy** [comment]
I am confused. If i this doesn't work how do i connect my tests ? I want the remote URL to connect to in Desired capabilities so that i can run the tests. In this case what would be remote driver URL ? Sorry i do not know GO programming

**Comment by alcounit** [comment]
Please check: https://github.com/alcounit/selenosis#run-yout-tests

**Comment by ShwethaParthasarathy** [comment]
Thanks for the reference. I was able to kick start the test. But i am not able to see the live recording. The VNc always shows as disconnected even though the vnc is set to true . Also i am unable to create a session. Using minikube to create containers on Mac. Selenium version is 3.141.59 - Below is the piece of code

 public void setupDriver() throws MalformedURLException {
      //CODE FOR SELENOID
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName(BrowserType.CHROME);
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", true);
        capabilities.setCapability("videoName", "demoVideoTest_2.mp4");
        this.driver = new RemoteWebDriver(new URL("http://<LB IP>:4444/wd/hub"), capabilities);
     }

Error is :
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities {browserName: chrome, enableVNC: true, enableVideo: true, videoName: demoVideoTest_2.mp4}
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'parthasaras-a01.vmware.com', ip: '192.168.0.201', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_251'
Driver info: driver.version: RemoteWebDriver

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:87)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at com.tests.BaseTest.setupDriver(BaseTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)
	at org.testng.TestRunner.beforeRun(TestRunner.java:613)
	at org.testng.TestRunner.run(TestRunner.java:584)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
<img width="1764" alt="Screen Shot 2022-03-17 at 10 27 51 PM" src="https://user-images.githubusercontent.com/64253396/158853751-ae5169f7-2789-4124-abdb-12579c15db11.png">

**Comment by alcounit** [comment]
selenosis doesn't support video recording.
can you please share selenosis logs, you can grab them using kubectl

**Comment by ShwethaParthasarathy** [comment]
This is the log that i see:
time="2022-03-18T00:56:37Z" level=info msg="starting selenosis v1.0.5"
time="2022-03-18T00:56:37Z" level=info msg="browsers config file loaded"
time="2022-03-18T00:56:37Z" level=info msg="config watcher started"
time="2022-03-18T00:56:37Z" level=info msg="kubernetes client created"
time="2022-03-18T00:56:37Z" level=info msg="current cluster state: sessions - 0, workers - 3, session limit - 10"
time="2022-03-18T00:56:37Z" level=info msg="selenosis worker: selenosis-58c9bf888c-sdhzl added, current namespace quota limit: 13"
time="2022-03-18T00:56:37Z" level=info msg="selenosis worker: selenosis-58c9bf888c-pfvl2 added, current namespace quota limit: 13"
time="2022-03-18T00:56:37Z" level=info msg="selenosis worker: selenoid-ui-5579768c8f-hcnzx added, current namespace quota limit: 13"
parthasarash@parthasaras-a01 selenosis-deploy % kubectl logs selenosis-58c9bf888c-sdhzl -n selenosis
time="2022-03-18T00:56:37Z" level=info msg="starting selenosis v1.0.5"
time="2022-03-18T00:56:37Z" level=info msg="browsers config file loaded"
time="2022-03-18T00:56:37Z" level=info msg="config watcher started"
time="2022-03-18T00:56:37Z" level=info msg="kubernetes client created"
time="2022-03-18T00:56:37Z" level=info msg="current cluster state: sessions - 0, workers - 3, session limit - 10"
time="2022-03-18T00:56:37Z" level=info msg="selenosis worker: selenosis-58c9bf888c-pfvl2 added, current namespace quota limit: 13"
time="2022-03-18T00:56:37Z" level=info msg="selenosis worker: selenoid-ui-5579768c8f-hcnzx added, current namespace quota limit: 13"
time="2022-03-18T00:56:37Z" level=info msg="selenosis worker: selenosis-58c9bf888c-sdhzl added, current namespace quota limit: 13"
time="2022-03-18T05:05:09Z" level=info msg=session request="POST /wd/hub/session" request_id=74ef0664-ae09-4274-9d38-a531785d327e time_elapsed=0.00s
time="2022-03-18T05:05:09Z" level=info msg="starting browser from image: selenoid/vnc:chrome_99.0" request="POST /wd/hub/session" request_id=74ef0664-ae09-4274-9d38-a531785d327e time_elapsed=0.00s
time="2022-03-18T05:05:41Z" level=error msg="failed to start browser: container service is not ready http://vnc-chrome-99-0-ee52cad2-84cb-41ec-aeeb-5a24aa0a9d26.seleniferous:4444" request="POST /wd/hub/session" request_id=74ef0664-ae09-4274-9d38-a531785d327e time_elapsed=32.32s

**Comment by alcounit** [comment]
Can you please update [03-selenosis.yaml](https://github.com/alcounit/selenosis-deploy/blob/a0e7989bb55792fa675501b4e57167adcf416596/03-selenosis.yaml#L24) file and add a few options at the end:
"--browser-wait-timeout", "1m30s", "--session-wait-timeout", "1m30s"
Redeploy selenosis with updated file.
These options increase wait for timeouts for browser and session.
Please let me know any result.

**Comment by alcounit** [comment]
Hi @ShwethaParthasarathy, any updates?

**Comment by ShwethaParthasarathy** [comment]
Hi,

Sorry didn't get a chance to try it out. Will do it on Monday and let you
know.

Thanks,
Shwetha

**Comment by ShwethaParthasarathy** [comment]
Hi,

It worked. able to run tests. Thanks! But i wanted to capture the video too. Any suggestions on how to do it ?  Also wanted to understand what are the layers in the image. 

Thanks,
Shwetha

**Comment by alcounit** [comment]
> But i wanted to capture the video too. Any suggestions on how to do it ?

this feature is not implemented, you can implement it if you want

> Also wanted to understand what are the layers in the image.

what image you are talking about?

**Comment by ShwethaParthasarathy** [comment]
> > But i wanted to capture the video too. Any suggestions on how to do it ?
> 
> this feature is not implemented, you can implement it if you want
> 
> > Also wanted to understand what are the layers in the image.
> 
> what image you are talking about?

I am talking about the selenosis and the seleniferous image that we use in selenosis yaml

**Comment by alcounit** [comment]
> I am talking about the selenosis and the seleniferous image that we use in selenosis yaml

You can check it with https://github.com/wagoodman/dive

Closing issue as the main question has been resolved.
